/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        bg:          "#F4EFE3",
        bgDeep:      "#EDE6D2",
        card:        "#FFFFFF",
        cardSoft:    "#FBF7EC",
        border:      "#E6DFC9",
        borderSoft:  "#EFE9D6",
        forest:      "#0B3B2E",
        forestMid:   "#145E47",
        forestDeep:  "#062319",
        emerald:     "#10B981",
        emeraldDeep: "#0E8F66",
        mint:        "#D5F2E3",
        lime:        "#A3E635",
        ink:         "#13201B",
        inkSoft:     "#4A584F",
        inkMute:     "#7A8780",
        inkFaint:    "#A8B0A6",
        amber:       "#E89E2A",
        amberBg:     "#FAEEC9",
        red:         "#D75A4E",
        redBg:       "#F8D9D2",
        violet:      "#7C6AE0",
        violetBg:    "#E5DFFA",
        sky:         "#3A8FD1",
      },
    },
  },
  plugins: [],
};
