# Alembic configuration file.

[alembic]
script_location = alembic
prepend_sys_path = .
sqlalchemy.url =

# use template to generate migration scripts
# file_template = %%(rev)s_%%(slug)s

# sys.path path, will be prepended to sys.path if present
# prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# string value is passed to datetime.tz module. leave blank
# for localtime
# timezone =

# max length of characters to apply to the
# "slug" field of the filename (template limitation)
# new_encoding = utf-8

# Logging configuration
[loggers]
keys = root,sqlalchemy.engine

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy.engine]
level = WARN
handlers =
qualname = sqlalchemy.engine

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
